[atlas]
size = 256
tile_size = 16
count = 256

[blocks]
	[blocks.stone]
	id = 1
	textures.all = { x = 0, y = 0 }

	[blocks.grass]
	id = 2
	textures.top = { x = 1, y = 0 }
	textures.bottom = { x = 2, y = 0 }
	textures.sides = { x = 3, y = 0 }

	[blocks.dirt]
	id = 3
	textures.all = { x = 2, y = 0 }

	[blocks.cobblestone]
	id = 4
	textures.all = { x = 4, y = 0 }

	[blocks.bedrock]
	id = 7
	textures.all = { x = 0, y = 1 }

	[blocks.sand]
	id = 12
	textures.all = { x = 5, y = 0 }

	[blocks.water]
	id = 17
	textures.all = { x = 0, y = 2 }
	transparency = true
