name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          make

    - name: Install Vulkan SDK
      shell: pwsh
      run: |
        $vulkanSdk = "C:\VulkanSDK"
        $version = "1.3.275.0"
        $installer = "VulkanSDK-$version-Installer.exe"
        $url = "https://sdk.lunarg.com/sdk/download/$version/windows/$installer"
        
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath ".\$installer" -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
        
        echo "VULKAN_SDK=$vulkanSdk\$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build
      run: |
        make release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          app.exe
          assets/**

    - name: Install Windows SDK components
      shell: pwsh
      run: |
        choco install windows-sdk-10-version-2004-all -y

    - name: Create self-signed certificate and sign app
      shell: pwsh
      run: |
        $cert = New-SelfSignedCertificate -Subject "CN=VulkanMinecraft" -Type CodeSigning -CertStoreLocation Cert:\CurrentUser\My
        $certPassword = ConvertTo-SecureString -String "tempPassword123!" -Force -AsPlainText
        Export-PfxCertificate -Cert "Cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath "certificate.pfx" -Password $certPassword

        $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter "signtool.exe" | 
                  Where-Object { $_.Directory.Name -match "x64" } | 
                  Select-Object -First 1 -ExpandProperty FullName
        
        & $signtool sign /f certificate.pfx /p "tempPassword123!" /fd sha256 /t http://timestamp.digicert.com /d "Vulkan Minecraft" app.exe