name: build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: "MSYS Makefiles"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            base-devel
            msys2-devel

      - name: Install Vulkan SDK
        run: |
          $vulkanSDK = "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe"
          Invoke-WebRequest -Uri $vulkanSDK -OutFile vulkan-sdk.exe
          Start-Process -FilePath "vulkan-sdk.exe" -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
        shell: pwsh

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake -G "MSYS Makefiles" ..

      - name: Build
        shell: msys2 {0}
        working-directory: build
        run: make release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-minecraft-release
          path: |
            build/app.exe
            assets/