name: Build

on:
  push:
    branches: [ dev ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          make

    - name: Install Vulkan SDK
      shell: pwsh
      run: |
        $vulkanSdk = "C:\VulkanSDK"
        $version = "1.3.275.0"
        $installer = "VulkanSDK-$version-Installer.exe"
        $url = "https://sdk.lunarg.com/sdk/download/$version/windows/$installer"
        
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath ".\$installer" -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
        
        echo "VULKAN_SDK=$vulkanSdk\$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build
      run: |
        make release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-minecraft-windows
        path: |
          app.exe
          assets/**